FROM heroku/heroku:16

MAINTAINER Jay <jay@imjching.com>

# Install daemontools so that setuidgid can be used
RUN apt-get -q update \
  && apt-get -yq --no-install-recommends install \
    apt-utils \
    daemontools \
    # gcc \
    # libgmp3-dev \
    # libpq-dev \
    # libssl-dev \
    # libxslt-dev \
    # libxml2-dev \
    # build-essentials \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Set environment variables
ENV HOME "/app"
ENV BUILDPACK_PATH "/tmp/buildpacks"
ENV CACHE_PATH "/tmp/cache"
ENV SHELL "/bin/bash"
ENV DOCK_GROUP "dyno"
ENV DOCK_USER "u32767"
ENV DOCK_UID "32767"
# ENV PS1 "\[\033[01;34m\]\w\[\033[00m\] \[\033[01;32m\]$ \[\033[00m\]"
ENV CURL_CONNECT_TIMEOUT "30"
ENV CURL_TIMEOUT "180"
ENV STACK "heroku-16"

# Create u32767 user with UID=32767 and add to 'dyno' group
RUN groupadd $DOCK_GROUP && \
    useradd -M -d $HOME -s $SHELL -g $DOCK_GROUP -u $DOCK_UID $DOCK_USER && \
    bash -c "mkdir -pv $HOME $BUILDPACK_PATH $CACHE_PATH" && \
    chown -R $DOCK_USER:$DOCK_GROUP $HOME && \
    chown -R $DOCK_USER:$DOCK_GROUP /tmp

# Setup slug runner
COPY ./build/linux/slugc /bin/slugc
RUN ln -s /bin/slugc /install && ln -s /bin/slugc /build

# Change user and working directory
USER $DOCK_USER
WORKDIR $HOME

RUN /install && rm -rf ~/.basher
